"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("mocha");
var Actor_1 = require("../../Model/Actor");
describe('Interaction', function () {
    it('should be resolvable having, at a minimum, been generated by a source actor and aimed at a target actor', function () {
        var a = new Actor_1.Actor();
        var b = new Actor_1.Actor();
    });
});
//# sourceMappingURL=Interaction.js.map