import {expect} from 'chai';
import 'mocha';

import {Actor} from "../../Model/Actor";

describe( 'Interaction', function() {

    it( 'should be resolvable having, at a minimum, been generated by a source actor and aimed at a target actor', function() {

        let a = new Actor();
        let b = new Actor();
    });

});